// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8d6wDNAi5gzOBkdJSL52uNXxnk-ZJzI4',
    appId: '1:301094016007:web:50db9a1806c28e84f806a2',
    messagingSenderId: '301094016007',
    projectId: 'proxi-job',
    authDomain: 'proxi-job.firebaseapp.com',
    storageBucket: 'proxi-job.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaMcXQgAVaa5LejBmVjs7JxCtKjey0Uos',
    appId: '1:301094016007:android:477482f17aecbec9f806a2',
    messagingSenderId: '301094016007',
    projectId: 'proxi-job',
    storageBucket: 'proxi-job.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1dRxTYV_iMw25pYILE5Dz9-KiQ09aaLM',
    appId: '1:301094016007:ios:d11c8fb797bccf72f806a2',
    messagingSenderId: '301094016007',
    projectId: 'proxi-job',
    storageBucket: 'proxi-job.firebasestorage.app',
    iosBundleId: 'com.example.proxiJob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1dRxTYV_iMw25pYILE5Dz9-KiQ09aaLM',
    appId: '1:301094016007:ios:d11c8fb797bccf72f806a2',
    messagingSenderId: '301094016007',
    projectId: 'proxi-job',
    storageBucket: 'proxi-job.firebasestorage.app',
    iosBundleId: 'com.example.proxiJob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8d6wDNAi5gzOBkdJSL52uNXxnk-ZJzI4',
    appId: '1:301094016007:web:aa12ee4b3741f4fcf806a2',
    messagingSenderId: '301094016007',
    projectId: 'proxi-job',
    authDomain: 'proxi-job.firebaseapp.com',
    storageBucket: 'proxi-job.firebasestorage.app',
  );
}
